username:           "admin"
password:           "Thinagar3821@"
server:             "THINAGAR"
driver:             "{ODBC Driver 17 for SQL Server}"
access_database:    "master"
create_database:    "DATA"
create_schema:      "SYNTHETIC"