server:               "Thinagar"
driver:               "{ODBC Driver 17 for SQL Server}"
database:             "DATA"
schema:               "SYNTHETIC"

db_admin:
  username:           "admin"
  password:           "Thinagar3821@"
  default_database:    "master"

db_user:
  username:           "naga"
  password:           "Thinagar3821@"